```{r setup, include = F}
# analysis
library(clusterProfiler)
library(factoextra)

# plotting
library(ComplexHeatmap)
library(pheatmap)
library(cowplot)

# databases
library(msigdbr)
library(org.Hs.eg.db)

# tidyverse
library(tidyverse)
```

```{r load helpers}
source("../R/helpers.R")
```

```{r load data}
source("../R/main-data.R")
```

```{r cluster kinetics}
# pick genes
goi_up = filter(tc_dea, treatment == "IL1B" & peak_sig == "up") %>% 
  pull(Gene) %>% 
  unique() %>% 
  sort()

goi_dn = filter(tc_dea, treatment == "IL1B" & peak_sig == "dn") %>% 
  pull(Gene) %>% 
  unique() %>% 
  sort()

# k-means function
run_kmeans <- function(
    geneList,
    dataFrame = tc_dea,
    clusterPrefix,
    nClusters,
    ttt = "IL1B",
    clusterOptimizationMode = F
){
    
    # build matrix
    mat = dataFrame %>%
      filter(treatment == ttt & Gene %in% geneList) %>%
      select(Gene, time, log2fold) %>%
      pivot_wider(names_from = "time", values_from = "log2fold") %>%
      column_to_rownames("Gene") %>%
      t() %>% scale() %>% t()
    
    if (!clusterOptimizationMode){
      
      # run clustering
      set.seed(777)
      clust = mat %>%
        kmeans(centers = nClusters, nstart = nClusters, iter.max = 100) %>%
        .$cluster %>%
        as.data.frame(nm = "cluster") %>%
        mutate(cluster = paste0(clusterPrefix, cluster)) %>%
        rownames_to_column("Gene")
      
      return(clust)
      
    }
    
    else {
      
      # optimize #clusters
      sil = fviz_nbclust(mat, kmeans, method = "silhouette", linecolor = "black")
      wss = fviz_nbclust(mat, kmeans, method = "wss", linecolor = "black")
      
      print(sil)
      print(wss)
      
    }
    
}

# run tests
run_kmeans(geneList = goi_up, clusterOptimizationMode = T)
run_kmeans(geneList = goi_dn, clusterOptimizationMode = T)

# run clustering
clust_up = run_kmeans(geneList = goi_up, clusterPrefix = "up_", nClusters = 6)
clust_dn = run_kmeans(geneList = goi_dn, clusterPrefix = "dn_", nClusters = 4)

# name clusters
cluster_assignments = rbind(clust_up, clust_dn) %>% 
  arrange(Gene) %>%
  mutate(
    cluster = factor(
      cluster,
      levels = c(
        "up_4", "up_3", "up_5", "up_2", "up_6", "up_1",
        "dn_4", "dn_3", "dn_1", "dn_2"
      )
    )
  ) %>%
  mutate(
    peak_sig = case_when(
      str_detect(cluster, "up_") ~ "up",
      str_detect(cluster, "dn_") ~ "dn"
    )
  ) %>%
  mutate(peak_sig = factor(peak_sig, levels = c("up", "dn"))) %>%
  mutate(
    shape = case_when(
      cluster == "up_4" ~ "immediate",
      cluster == "up_3" ~ "early",
      cluster == "up_5" ~ "mid",
      cluster == "up_2" ~ "mid-late",
      cluster == "up_6" ~ "late",
      cluster == "up_1" ~ "sustained",
      cluster == "dn_4" ~ "early",
      cluster == "dn_3" ~ "mid",
      cluster == "dn_1" ~ "mid-late",
      cluster == "dn_2" ~ "late"
    )
  ) %>%
  mutate(
    shape = factor(
      shape,
      levels = c(
        "immediate", "early", "mid", "mid-late", "late", "sustained"
      )
    )
  ) %>%
  mutate(groupName = paste0(peak_sig, "_", shape)) %>%
  left_join(
    tc_dea %>%
      filter(treatment == "IL1B") %>%
      select(Gene, peak) %>%
      distinct(),
    by = "Gene"
  )

# check clusters
df = tc_dea %>%
  left_join(cluster_assignments, by = "Gene") %>%
  filter(
    !is.na(cluster),
    treatment == "IL1B"
    )

ggplot(
  df,
  aes(x = time, y = log2fold)
  ) +
  facet_wrap(~cluster) +
  stat_summary(
    aes(group = cluster),
    geom = "line",
    fun = "mean"
    ) +
  geom_hline(yintercept = 0, linetype = "dashed")

saveRDS(cluster_assignments, "../results/figure2/cluster_assignments.rds")

writexl::write_xlsx(cluster_assignments, "../results/figure2/cluster_assignments.xlsx")

cleanup_objects()
```

```{r fig 2a, fig.height=6, fig.width=3}
df = tc_dea %>%
  left_join(cluster_assignments, by = c("Gene", "peak_sig")) %>%
  filter(
    !is.na(cluster),
    treatment == "IL1B"
    )

ggplot(
  df,
  aes(x = time, y = log2fold)
) +
  facet_grid(
    shape~peak_sig,
    labeller = labeller(
      peak_sig = c(
        "up" = "upreg",
        "dn" = "downreg"
      )
    )
  ) +
  geom_line(
    aes(group = Gene),
    alpha = 0.1
  ) +
  stat_summary(
    geom = "line",
    fun = "mean",
    aes(group = cluster, color = peak_sig),
    lwd = 1
  ) +
  geom_hline(
    yintercept = 0,
    linetype = "dashed",
    color = "black",
    lwd = 0.5
  ) +
  coord_cartesian(
    ylim = c(3, -3)
  ) +
  scale_color_manual(
    values = c("firebrick2", "steelblue2")
  ) +
  scale_x_discrete(
    expand = expansion(mult = 0.05)
  ) +
  theme_bw() +
  theme(
    aspect.ratio = 1,
    strip.background = element_blank(),
    panel.grid = element_blank(),
    legend.position = "none"
  ) +
  labs(
    x = "time (h)",
    y = "log2fold"
  )

# count genes in each cluster
cluster_assignments %>%
  select(Gene, groupName) %>%
  distinct() %>%
  count(groupName)

cleanup_objects()
```

```{r run gene ontology}
# # enrichGO function
# run_enrichGO <- function(
#   geneList,
#   geneUniverse = unique(tc_tpm$Gene),
#   geneOntology = "BP",
#   groupName = "groupName",
#   simplify = F
# ){
# 
#   print(paste("Running GO with", geneOntology, "on group", groupName, "..."))
# 
#   go = enrichGO(
#     gene = geneList,
#     universe = geneUniverse,
#     OrgDb = org.Hs.eg.db,
#     keyType       = "SYMBOL",
#     ont           = geneOntology,
#     pAdjustMethod = "BH",
#     qvalueCutoff  = 0.05,
#     readable      = TRUE
#   )
# 
#   if (simplify){
# 
#     print("Simplifying...")
# 
#     go <- clusterProfiler::simplify(
#       go,
#       cutoff = 0.7,
#       by = "p.adjust",
#       select_fun = min
#     )
# 
#   }
# 
#   go@result %>%
#     mutate(groupName = groupName, .before = 1) %>%
#     mutate(Ontology = geneOntology, .before = ID)
# 
# }
# 
# 
# # run enrichGO over all clusters
# 
# all_genes = unique(tc_tpm$Gene)
# 
# clusters_enrichGO = list()
# 
# 
# for(gn in unique(cluster_assignments$groupName)){
# 
#   genelist = cluster_assignments %>%
#     filter(groupName == gn) %>%
#     pull(Gene)
# 
#   bp = run_enrichGO(
#     genelist,
#     all_genes,
#     "BP",
#     gn,
#     simplify = T
#   )
# 
#   mf = run_enrichGO(
#     genelist,
#     all_genes,
#     "MF",
#     gn,
#     simplify = T
#   )
# 
#   df = rbind(bp, mf)
# 
#   clusters_enrichGO[[gn]] = df
# }
# 
# saveRDS(clusters_enrichGO, "../results/figure2/clusters_enrichGO.rds")
clusters_enrichGO = readRDS("../results/figure2/clusters_enrichGO.rds")

# cleanup_objects()
```

```{r fig 2b and fig 2c, fig.height=2, fig.width=5}
clusters_enrichGO = read_rds("../results/figure2/clusters_enrichGO.rds")

# function to prepare dataframes
prep_go <- function(
    df,
    countThreshold = 15,
    nTerms = 10
    ) {
  
  df %>%
    filter(Count >= countThreshold, p.adjust <= 0.05) %>%
    slice_max(FoldEnrichment, n = nTerms, with_ties = FALSE) %>%
    mutate(
      Description = str_wrap(str_trunc(Description, 60), 35),
      Description = factor(Description, levels = rev(Description))
    )
  
}



# function to generate the base plot
base_plot <- function(
    df, 
    title = NULL,
    size_limits = NULL,
    x_limits = NULL,
    fill_limits = NULL) {
  ggplot(
    df,
    aes(
      x = FoldEnrichment,
      y = Description,
      fill = -log10(p.adjust),
      size = Count
    )
  ) +
    geom_point(shape = 21) +
    scale_size(
      limits = size_limits, range = c(2, 8), breaks = scales::breaks_pretty(n=3)
    ) +
    viridis::scale_fill_viridis(
      option = "viridis",
      limits = fill_limits
    ) +
    scale_x_continuous(
      limits = x_limits,
      expand = expansion(mult = 0.15),
      breaks = scales::breaks_pretty(n = 3)
    ) +
    labs(
      x = "fold enrichment", 
      y = title,
      size = "count",
      fill = expression(log[10] * "FDR")
    ) +
    theme_bw() +
    theme(
      aspect.ratio = 2,
      panel.grid.minor = element_blank()
    )
}

# plots

fillLimits = c(0, 40)
sizeLimits = c(1, 60)

base_plot(
  prep_go(clusters_enrichGO[["up_immediate"]], nTerms = 5, countThreshold = 5), 
  "up_immediate", 
  fill_limits = fillLimits,
  size_limits = sizeLimits
  
  )

base_plot(
  prep_go(clusters_enrichGO[["up_early"]], nTerms = 5), 
  "up_early", 
  fill_limits = fillLimits,
  size_limits = sizeLimits
  
  )

base_plot(
  prep_go(clusters_enrichGO[["up_mid"]], nTerms = 5), 
  "up_mid", 
  fill_limits = fillLimits,
  size_limits = sizeLimits
  )

base_plot(
  prep_go(clusters_enrichGO[["up_mid-late"]], nTerms = 5), 
  "up_mid-late", 
  fill_limits = fillLimits,
  size_limits = sizeLimits
  )

base_plot(
  prep_go(clusters_enrichGO[["up_late"]], nTerms = 5, countThreshold = 10), 
  "up_late", 
  fill_limits = fillLimits,
  size_limits = sizeLimits
  )

base_plot(
  prep_go(clusters_enrichGO[["up_sustained"]], nTerms = 5), 
  "up_sustained", 
  fill_limits = fillLimits,
  size_limits = sizeLimits
  )

# ===========

base_plot(
  prep_go(clusters_enrichGO[["dn_early"]], countThreshold = 5, nTerms = 5), 
  "dn_early", 
  fill_limits = fillLimits,
  size_limits = sizeLimits
  )

base_plot(
  prep_go(clusters_enrichGO[["dn_mid"]], countThreshold = 15, nTerms = 5), 
  "dn_mid", 
  fill_limits = fillLimits,
  size_limits = sizeLimits
  )

base_plot(
  prep_go(clusters_enrichGO[["dn_mid-late"]], countThreshold = 15, nTerms = 5), 
  "dn_mid-late", 
  fill_limits = fillLimits,
  size_limits = sizeLimits
  )

base_plot(
  prep_go(clusters_enrichGO[["dn_late"]], countThreshold = 5, nTerms = 5), 
  "down_late", 
  fill_limits = fillLimits,
  size_limits = sizeLimits
  )

```




```{r find example genes}
cluster_candidates = tibble()

for(gn in unique(cluster_assignments$groupName)){
  
  g = cluster_assignments %>%
    filter(groupName == gn) %>%
    pull(Gene)
  
  mat = tc_dea %>%
    filter(treatment == "IL1B", Gene %in% g) %>%
    select(Gene, time, log2fold) %>%
    pivot_wider(values_from = "log2fold", names_from = "time") %>%
    column_to_rownames("Gene") %>%
    as.matrix() %>%
    t() %>% scale() %>% t()
  
  centroid = colMeans(mat)
  
  cor_to_centroid = apply(mat, 1, function(x) {cor(x, centroid)})
  
  df = data.frame(correlation = cor_to_centroid) %>%
    rownames_to_column("Gene") %>%
    arrange(desc(correlation)) %>%
    slice_head(n = 20) %>%
    mutate(groupName = gn, .before = 1)
  
  cluster_candidates = rbind(cluster_candidates, df)
  
}

saveRDS(cluster_candidates, "../results/figure2/cluster_candidates.rds")
write_tsv(cluster_candidates, "../results/figure2/cluster_candidates.txt")

cleanup_objects()
```

```{r plot example genes, fig.height=2, fig.width=2}
ggplot(
  filter(tc_tpm, Gene == "ICAM1", treatment == "IL1B"),
  aes(x = time, y = log2fold, group = Gene)
) +
  facet_wrap(~Gene) +
  stat_summary(geom = "point", fun = "mean") +
  stat_summary(geom = "errorbar", fun.data = "mean_sdl", fun.args = list(mult = 1),
               width = 0.3) +
  stat_summary(geom = "line", fun = "mean") +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    aspect.ratio = 1
  )
```



```{r peak times of each cluster, fig.height=6, fig.width=3}

# most of the clusters correspond to peak-time groups, but mid-late and 
# sustained capture trajectory properties that peak time alone misses...

# we see "dominant-peak" clusters (e.g., immediate, early, mid, late), where
# the peak aligns nicely with the kinetic.

# we also see "distributed-peak" clusters (e.g., mid-late, sustained), where
# peak times are mixed

# dominant-peak clusters can take viper right at the peak time, but distributed-
# peak clusters should retain kinetic and take viper at all timepoints

df = cluster_assignments %>%
  group_by(peak_sig, shape) %>%
  count(peak) %>%
  mutate(total = sum(n)) %>%
  mutate(fraction = n/total) %>%
  ungroup()

ggplot(
  df,
  aes(x = 1, y = fraction, fill = peak)
) +
  facet_grid(
    shape~peak_sig,
    labeller = labeller(
      peak_sig = c(
        "up" = "upreg",
        "dn" = "downreg"
      )
    )
  ) +
  geom_col(
    color = "black"
  ) +
  coord_polar(theta = "y") +
  theme_void()

df2 = cluster_assignments %>%
  group_by(peak_sig, peak) %>%
  count(shape) %>%
  mutate(total = sum(n)) %>%
  mutate(fraction = n/total) %>%
  ungroup()

ggplot(
  df2,
  aes(x = 1, y = fraction, fill = shape)
) +
  facet_grid(
    peak~peak_sig,
    labeller = labeller(
      peak_sig = c(
        "up" = "upreg",
        "dn" = "downreg"
      )
    )
  ) +
  geom_col(
    color = "black"
  ) +
  coord_polar(theta = "y") +
  theme_void()

cleanup_objects()
```

```{r run viper/aREA on clusters, fig.height=5, fig.width=3}

# get transcription factor regulon info
source("../R/get-dorothea-regulons.R")

# for dominant-peak clusters, we can simply take peak gene expression
# and ask which transcription factor are enriched.
# this can be done with aREA (without wrapping in VIPER, which handles
# between-sample comparisons)

# conceptually similar to rigging up a custom GSEA geneset, but aREA
# can make use of doRothEA's confidence and directional info.

cluster_to_peak <- c(
  up_immediate = 1,
  up_early = 2,
  up_mid = 6,
  up_late = 24
)

aREA_results <- list()

for (g in names(cluster_to_peak)) {
  
  t <- cluster_to_peak[g]
  
  goi <- cluster_assignments %>%
    filter(groupName == g) %>%
    pull(Gene)
  
  mat <- tc_dea %>%
    filter(
      treatment == "IL1B",
      time == t,
      Gene %in% goi
    ) %>%
    select(Gene, log2fold) %>%
    column_to_rownames("Gene") %>%
    as.matrix()
  
  aREA_results[[g]] <- viper::aREA(
    mat[, 1],
    dorothea_regulons[["viper_input"]],
    minsize = 10
  )$nes %>%
    as.data.frame() %>%
    rename(NES = V1) %>%
    rownames_to_column("tf") %>%
    mutate(
      groupName = g,
      time = t,
      .before = 1
    )
}

aREA_results <- bind_rows(aREA_results) %>%
  mutate(
    groupName = factor(groupName, levels = unique(groupName)),
    time = factor(time, levels = unique(time))
  )

ggplot(aREA_results, aes(x = NES, y = reorder(tf, NES))) +
  facet_wrap(
    ~ groupName, 
    scales = "free_y",
    ncol = 1
    ) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_col() +
  labs(
    x = "aREA NES",
    y = "TF"
  )

cleanup_objects()



# todo: for distributed-peak genes, run full VIPER on all times and
# look for interesting patterns within peak subpopulations.
```

```{r viper on clusters}
# temporal emergence of STAT/IRF regulatory activity during a sustained NFkB response

# get transcription factor regulon info
source("../R/get-dorothea-regulons.R")

activity_matrices = list()

for (g in c(
  "up_immediate",
  "up_early",
  "up_mid",
  "up_mid-late",
  "up_late",
  "up_sustained"
)){
  
  goi = cluster_assignments %>%
    filter(groupName == g) %>%
    pull(Gene)
  
  min_size = min(
    round(length(goi) * 0.1, 0),
    10
  )
  
  # min_size = 10
  # print(paste0(g, " ", min_size))
  
  mat = tc_dea %>%
    filter(treatment == "IL1B", Gene %in% goi) %>%
    select(Gene, time, log2fold) %>%
    pivot_wider(values_from = "log2fold", names_from = "time") %>%
    column_to_rownames("Gene") %>%
    as.matrix()

  activity = tryCatch(
    viper::viper(
      mat,
      dorothea_regulons[["viper_input"]],
      minsize = min_size,
      verbose = F
    ),
    error = function(e) {
      message("Skipped ", g, ": ", e$message)
      return(NULL)
    }
  )

  if (!is.null(activity)) {
    activity_matrices[[g]] = activity
  }

  rm(g, goi, min_size, mat, activity)
}

for(nm in names(activity_matrices)){
  
  mat = activity_matrices[[nm]]
  colors = generic_l2f_heatmap_colors(mat)
  
  print(
    Heatmap(
      mat,
      column_title = nm,
      cluster_columns = FALSE,
      col = colors
    )
  )
  
  rm(nm, mat, colors)
}

```





























