```{r setup, include = F}
# analysis
library(clusterProfiler)
library(viper)

# plotting
library(ComplexHeatmap)
library(pheatmap)
library(cowplot)

# databases
library(dorothea)

# tidyverse
library(tidyverse)
```

```{r load helpers}
source("../R/helpers.R")
```

```{r load data}
source("../R/main-data.R")
```

```{r run viper}
# import dorothea data
regulons <- dorothea_hs %>%
  filter(confidence %in% c("A", "B", "C")) %>%
  mutate(likelihood = case_when(
    confidence == "A" ~ 1.00,
    confidence == "B" ~ 0.75,
    confidence == "C" ~ 0.50
  ))

regulons_summary <- regulons %>%
  group_by(tf) %>%
  summarize(
    max_confidence = if_else("A" %in% confidence, "A", if_else("B" %in% confidence, "B", "C")),
    n_targets      = length(unique(target)),
    target_list    = list(target)
  )

rg <- regulons %>%
  split(.$tf) %>%
  map(~list(
    tfmode     = setNames(.x$mor, .x$target),
    likelihood = setNames(.x$likelihood, .x$target)
  ))

# run VIPER on IL1B-regulated genes under IL1B stim
mat = tc_dea %>%
  filter(treatment == "IL1B" & Gene %in% goi) %>%
  select(Gene, time, log2fold) %>%
  pivot_wider(names_from = "time", values_from = "log2fold") %>%
  column_to_rownames("Gene")

mat_viper = viper(mat, rg, minsize = 10)

saveRDS(mat_viper, "../results/figure3/mat_viper.rds")

cleanup_objects()
```

Heatmap of top 10 VIPER TFs:

```{r fig ???, fig.height=5, fig.width=4}
mat_viper = readRDS("../results/figure3/mat_viper.rds")

tfs_of_interest = mat_viper %>%
  as.data.frame() %>%
  rownames_to_column("tf") %>%
  group_by(tf) %>%
  mutate(abs = max(abs(c(`1`, `2`, `6`, `12`, `24`)))) %>%
  ungroup() %>%
  dplyr::slice_max(abs, n = 20) %>%
  pull(tf)

top_tfs_mat = mat_viper[tfs_of_interest, ]

colors = circlize::colorRamp2(
  seq(-10, 10, length = 200),
  colorRampPalette(
    c("orchid4", "orchid2", "white", "aquamarine2", "aquamarine4")
  )(200)
)

Heatmap(
  top_tfs_mat,
  cluster_columns = F,
  cluster_rows = T,
  clustering_method_rows = "ward.D2",
  row_split = 3,
  col = colors,
  border = "black",
  rect_gp = gpar(col = "black", lwd = 0.5),
  name = "NES",
  row_title = NULL,
  column_names_rot = 0,
  column_names_centered = T
)
```

