```{r setup, include = F}
# analysis
library(clusterProfiler)

# plotting
library(ComplexHeatmap)
library(pheatmap)
library(cowplot)

# databases
library(msigdbr)

# tidyverse
library(tidyverse)
```

```{r load helpers}
source("../R/helpers.R")
```

```{r load data}
source("../R/main-data.R")
```

3431 genes that are regulated by IL1B at any time.

```{r genes of interest}
# identify genes
goi = tc_dea %>%
  filter(treatment == "IL1B" & sig != "ns") %>%
  pull(Gene) %>%
  unique()
```

3394 genes that are regulated by IL1B at their peak

```{r genes of interest}
# identify genes
goi2 = tc_dea %>%
  filter(treatment == "IL1B" & peak_sig != "ns") %>%
  pull(Gene) %>%
  unique()
```

Number of genes that are up- or down-regulated.

```{r fig 1a, fig.height=2.5, fig.width=2}
df = tc_dea %>%
  filter(treatment == "IL1B" & sig != "ns") %>%
  select(Gene, sig) %>%
  distinct() %>%
  count(sig)

ggplot(df, aes(x = sig, y = n)) +
  geom_col() +
  geom_text(aes(label = n), vjust = -1) +
  theme(aspect.ratio = 2.5) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2)))

cleanup_objects()
```

Number of genes that are up- or down-regulated at each peak

```{r fig 1b, fig.height=2.5, fig.width=3}
df = tc_dea %>%
  filter(treatment == "IL1B" & peak_sig != "ns") %>%
  select(Gene, peak_sig, peak) %>%
  distinct() %>%
  count(peak_sig, peak)

ggplot(df, aes(x = peak, y = n)) +
  facet_wrap(~peak_sig) +
  geom_col() +
  geom_text(aes(label = n), vjust = -1) +
  theme(aspect.ratio = 1.5) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2)))

cleanup_objects()
```

PCA and Euclidean distances

```{r fig 1c, fig.height=2.5, fig.width=3}

# related to il1b-bud-timecourse/modules/pca.R

# -------------------------------------------------------------------------
# Prepare matrix
# -------------------------------------------------------------------------

mat = tc_tpm %>%
  filter(
    treatment %in% c("NS", "IL1B")
  ) %>%
  mutate(
    sample = paste(treatment, time, rep)
  ) %>%
  select(Gene, sample, log2tpm) %>%
  pivot_wider(
    names_from = sample,
    values_from = log2tpm
  ) %>%
  column_to_rownames("Gene") %>%
  as.matrix()

# Remove genes with zero variance
mat = mat[
  apply(mat, 1, var, na.rm = TRUE) > 0,
  ,
  drop = FALSE
]

# -------------------------------------------------------------------------
# PCA
# -------------------------------------------------------------------------

pca = prcomp(
  t(mat),
  center = TRUE,
  scale. = FALSE
)

# Percent variance explained
percent_var = 100 * pca$sdev^2 / sum(pca$sdev^2)

# Axis labels
pc1_label = paste0("PC1 (", round(percent_var[1], 1), "%)")
pc2_label = paste0("PC2 (", round(percent_var[2], 1), "%)")

# -------------------------------------------------------------------------
# PCA dataframe
# -------------------------------------------------------------------------

pca_df = as.data.frame(pca$x) %>%
  rownames_to_column("sample") %>%
  separate(
    sample,
    into = c("treatment", "time", "rep"),
    sep = " "
  ) %>%
  mutate(
    treatment = factor(
      treatment,
      levels = c("NS", "IL1B")
    ),
    time = factor(
      time,
      levels = c(1, 2, 6, 12, 24)
    )
  )

# -------------------------------------------------------------------------
# Distance of IL1B samples from matched NS samples
# -------------------------------------------------------------------------

pca_distance = pca_df %>%
  select(
    treatment,
    rep,
    time,
    PC1,
    PC2
  ) %>%
  left_join(
    pca_df %>%
      filter(treatment == "NS") %>%
      select(
        rep,
        time,
        PC1,
        PC2
      ) %>%
      rename(
        PC1_NS = PC1,
        PC2_NS = PC2
      ),
    by = c("rep", "time")
  ) %>%
  filter(treatment != "NS") %>%
  mutate(
    dist = sqrt(
      (PC1 - PC1_NS)^2 +
      (PC2 - PC2_NS)^2
    )
  ) %>%
  select(
    treatment,
    time,
    rep,
    dist
  )

# -------------------------------------------------------------------------
# PCA plot
# -------------------------------------------------------------------------

ggplot(
  pca_df,
  aes(
    x = PC1,
    y = PC2
  )
) +
  geom_point(
    aes(
      color = time,
      shape = treatment
    )
  ) +
  theme(
    aspect.ratio = 1
  ) +
  labs(
    x = pc1_label,
    y = pc2_label,
    color = NULL,
    shape = NULL
  )

# -------------------------------------------------------------------------
# Distance from matched NS
# -------------------------------------------------------------------------

ggplot(
  pca_distance,
  aes(
    x = time,
    y = dist
  )
) +
  stat_summary(
    geom = "col",
    fun = "mean"
  ) +
  geom_point(
    shape = 21,
    fill = "white"
  ) +
  labs(
    x = "Time",
    y = "Euclidean distance from NS"
  )


cleanup_objects()
```

DEG heatmap

```{r fig 1d, fig.height=4, fig.width=4, dpi=600}
# related to il1b-timecourse/modules/fig-il1b-heatmap.R

goi_up <- tc_dea %>%
  filter(
    peak_sig == "up",
    treatment == "IL1B"
  ) %>%
  pull(Gene) %>%
  unique() %>%
  sort()

goi_dn <- tc_dea %>%
  filter(
    peak_sig == "dn",
    treatment == "IL1B"
  ) %>%
  pull(Gene) %>%
  unique() %>%
  sort()

# -------------------------------------------------------------------------
# Matrix
# -------------------------------------------------------------------------

mat <- tc_tpm %>%
  filter(treatment == "IL1B") %>%
  mutate(
    sample = paste0("t", time, "h ", rep)
  ) %>%
  select(
    Gene,
    sample,
    log2fold
  ) %>%
  pivot_wider(
    names_from = "sample",
    values_from = "log2fold"
  ) %>%
  select(
    Gene,
    contains("t1h"),
    contains("t2h"),
    contains("t6h"),
    contains("t12h"),
    contains("t24h")
  ) %>%
  column_to_rownames("Gene") %>%
  as.matrix()

# -------------------------------------------------------------------------
# Z-score trajectories for clustering
# -------------------------------------------------------------------------

mat_up = mat[goi_up, , drop = FALSE]
mat_dn = mat[goi_dn, , drop = FALSE]

mat_up_z = t(scale(t(mat_up)))
mat_dn_z = t(scale(t(mat_dn)))

# Remove genes that cannot be z-scored
mat_up_z = mat_up_z[
  complete.cases(mat_up_z),
  ,
  drop = FALSE
]

mat_dn_z = mat_dn_z[
  complete.cases(mat_dn_z),
  ,
  drop = FALSE
]

# Keep raw matrices synchronized with z-scored matrices
mat_up = mat_up[rownames(mat_up_z), , drop = FALSE]
mat_dn = mat_dn[rownames(mat_dn_z), , drop = FALSE]

# -------------------------------------------------------------------------
# Determine number of clusters
# -------------------------------------------------------------------------

cluster_diagnostics(
  mat_up_z,
  method = "ward.D2"
)

cluster_diagnostics(
  mat_dn_z,
  method = "ward.D2"
)

# -------------------------------------------------------------------------
# Perform clustering on z-scored trajectories
# -------------------------------------------------------------------------

hc_up = hclust(
  dist(mat_up_z),
  method = "ward.D2"
)

hc_dn = hclust(
  dist(mat_dn_z),
  method = "ward.D2"
)

# Set chosen number of clusters
k_up = 4
k_dn = 3

clusters_up = cutree(
  hc_up,
  k = k_up
)

clusters_dn = cutree(
  hc_dn,
  k = k_dn
)

# -------------------------------------------------------------------------
# Order raw log2FC matrices according to z-score clustering
# -------------------------------------------------------------------------

mat_up = mat_up[
  hc_up$order,
  ,
  drop = FALSE
]

mat_dn = mat_dn[
  hc_dn$order,
  ,
  drop = FALSE
]

# Cluster assignments in the same order as the heatmap
clusters_up = clusters_up[
  rownames(mat_up)
]

clusters_dn = clusters_dn[
  rownames(mat_dn)
]

# -------------------------------------------------------------------------
# Heatmap setup
# -------------------------------------------------------------------------

colors = generic_l2f_heatmap_colors(
  c(mat_up, mat_dn)
)

columnSplits = factor(
  c(
    rep("1", 4),
    rep("2", 4),
    rep("6", 4),
    rep("12", 4),
    rep("24", 4)
  ),
  levels = c(
    "1",
    "2",
    "6",
    "12",
    "24"
  )
)

# -------------------------------------------------------------------------
# Upregulated genes
# -------------------------------------------------------------------------

Heatmap(
  mat_up,
  col = colors,
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  show_row_dend = FALSE,
  show_column_dend = FALSE,
  show_row_names = FALSE,
  show_column_names = FALSE,
  column_split = columnSplits,
  row_split = clusters_up,
  border = TRUE,
  use_raster = TRUE,
  name = "log2fold"
)

# -------------------------------------------------------------------------
# Downregulated genes
# -------------------------------------------------------------------------

Heatmap(
  mat_dn,
  col = colors,
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  show_row_dend = FALSE,
  show_column_dend = FALSE,
  show_row_names = FALSE,
  show_column_names = FALSE,
  column_split = columnSplits,
  row_split = clusters_dn,
  border = TRUE,
  use_raster = TRUE,
  name = "log2fold"
)

cleanup_objects()


```

GSEA on all heatmap genes

```{r fig 1e}
# format hallmark for clusterProfiler
hallmark <- msigdbr(species = "Homo sapiens", category = "H") %>%
  select("gs_name", "gene_symbol")

# get ranked list of genes at their peak
ranks = tc_dea %>%
  filter(treatment == "IL1B", time == peak) %>%
  select(Gene, log2fold) %>%
  arrange(desc(log2fold)) %>%
  deframe()

# # run gsea
# gsea = GSEA(
#   geneList = ranks,
#   TERM2GENE = hallmark,
#   pvalueCutoff = 1,
#   verbose = F
# )
# 
# gsea_df = gsea %>%
#   as.tibble() %>%
#   select(
#     Description,
#     NES,
#     p.adjust
#   ) %>%
#   mutate(
#     Description = gsub("HALLMARK_", "", Description),
#     Description = gsub("_", " ", Description)
#     ) %>%
#   arrange(NES) %>%
#   mutate(Description = factor(Description, levels = unique(Description)))
# 
# write_tsv(gsea_df, "../results/figure1/gsea_df.txt")

gsea_df = read_tsv("../results/figure1/gsea_df.txt") %>%
  mutate(Description = factor(Description, levels = unique(Description)))
  
ggplot(
  gsea_df %>% filter(p.adjust <= 0.05),
  aes(x = NES, y = Description, fill = -log10(p.adjust))
) +
  geom_col() +
  theme_bw() +
  theme(
    aspect.ratio = 3,
    panel.grid = element_blank()
  ) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "black", lwd = 0.5) +
  labs(
    fill = expression(-log[10] * "(FDR)"),
    y = NULL,
    x = "direction (NES)"
  )

barplot(ranks)

cleanup_objects()
```


GO on each timepoint

```{r fig 1f}

# ========================================
#               run GO
# ========================================


# tc_go_bp = data.frame()
# 
# 
# for(t in c(1, 2, 6, 12, 24)){
#   
#   genelist = tc_dea %>%
#     filter(time == t, sig != "ns") %>%
#     pull(Gene)
#   
#   print(paste0("Running ", t, "h..."))
#   
#   go_bp <- enrichGO(
#     gene = genelist,
#     universe = unique(tc_dea$Gene),
#     OrgDb = org.Hs.eg.db::org.Hs.eg.db,
#     keyType = "SYMBOL",
#     ont = "BP",
#     pAdjustMethod = "BH",
#     pvalueCutoff = 0.05,
#     readable = TRUE
#   )
#   
#   print(paste0("Simplifying ", t, "h..."))
#   
#   go_bp_simp = clusterProfiler::simplify(go_bp)
#   
#   df = go_bp_simp@result %>%
#     mutate(treatment = "IL1B", time = t, .before = 1)
#   
#   tc_go_bp = rbind(tc_go_bp, df)
# }
# 
# saveRDS(tc_go_bp, "../results/figure1/tc_go_bp.rds")
tc_go_bp = readRDS("../results/figure1/tc_go_bp.rds")

# ========================================
#             term selection
# ========================================

# strip out redundant "x" vs "regulation of x" terms
df_filtered <- tc_go_bp %>%
  mutate(
    Description_clean = str_remove(Description, "^regulation of "),
    GeneRatio = Count / as.numeric(sub(".*/", "", GeneRatio))
  ) %>%
  group_by(time, Description_clean) %>%
  slice_min(p.adjust, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  filter(GeneRatio >= 0.05)

# sequentially select terms; earlier timepoints get first dibs
claimed <- character()
df_list <- list()

for (t in c(1, 2, 6, 12, 24)) {
  
  tmp <- df_filtered %>%
    filter(
      time == t,
      !Description_clean %in% claimed
    ) %>%
    arrange(desc(FoldEnrichment)) %>%
    slice_head(n = 5)
  
  df_list[[as.character(t)]] <- tmp
  
  claimed <- c(claimed, tmp$Description_clean)
}

# assemble final dataframe
df_final <- bind_rows(df_list) %>%
  mutate(
    Description = factor(
      Description_clean,
      levels = rev(unique(Description_clean))
    )
  )


# default: only show the timepoint where each term was claimed
df_plot <- df_final


# ========================================
#           join in all appearances
# ========================================

df_plot <- df_filtered %>%
  filter(Description_clean %in% df_final$Description_clean) %>%
  left_join(
    df_final %>%
      select(Description_clean, claimed_time = time) %>%
      distinct(),
    by = "Description_clean"
  ) %>%
  mutate(
    claimed = time == claimed_time,
    Description = factor(
      Description_clean,
      levels = levels(df_final$Description)
    )
  )


# ========================================
#             plotting
# ========================================

ggplot(df_plot, aes(
  x = factor(time),
  y = Description,
  size = RichFactor,
  color = -log10(p.adjust),
  alpha = claimed
)) +
  geom_point(stroke = NA) +
  scale_alpha_manual(
    values = c(0.3, 1),
    guide = "none"
  ) +
  theme(
    aspect.ratio = 3
  ) +
  scale_color_gradient(low = "steelblue2", high = "firebrick2")


# cleanup_objects()
```











